# Set status bar to a dark grey background with light grey text
set -g status-style bg=default,fg=white

# Make the status bar less prominent
set -g status-left ''
set -g status-right ''
set -g status-justify centre
set -g mouse on